version: 2
jobs:
  build:
    working_directory: ~/working_directory
    docker:
      - image: node:6
    steps:
      - sudo apt-get install wget
      - sudo apt-get install g++
      - make profile-build ARCH=x86-64-bmi2 COMP=mingw
      - wget --no-check-certificate https://github.com/lantonov/asmFish/raw/master/fasmg
